// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/


 int mob_mvp_skill_rate;
 int max_sell_item_cap;
 int max_seal_item_val;
 int config_equipment_drop_auto_identify;
 int config_random_monster_rank;
 int config_monster_rank_damage_mode;
 int config_monster_rank_defense_mode;
 int config_monster_rank_exp_bonus_mode;
 int config_monster_rank_drop_bonus_mode;
 int config_enchantment_clickable;
 int config_enchantment_maximum;